const gallery = await MyGallery.deployed()
gallery.mint(accounts[0], "QmS4t7rFPxaaNriXvCmALr5GYRAtya5urrDaZgkfHutdCG")
gallery.mint(accounts[0], "QmXXtPjgeunQU6kxLdXJ2SDwu2TJtYjA9tHceQ5XtShkWo")
gallery.mint(accounts[0], "QmejUVxERZi1hTKTxJfSyK5x5KWzSgSBPChjZGWPj9TALj")
gallery.mint(accounts[0], "QmZYxFnayjhnEFddE2mrs563RjvZbQbrZ9hZKY1wCWMPCK")
